- Where do we want to check for valid input?
- *TODO* resolve terminology
  - change instances of "matrix" to "board" in game.cljs
- re-write table-row using output-row format


* output table thoughts:
- have a css class for cells which are restricted by input
- ? have a css class for cells which we can determine by ruleset
- ? have control panel to decide which propagation rules we will apply
- ? ability to hover restricted numbers to see which propagation rule determined restriction
- *BIG QUESTION*:
  - Do we want to completely recalculate output table on each update
    - or, is it possible + more efficient to mutate state
    - or can we somehow memoize?
    
* re-frame notes
- events :: sent by dispatch - composed of a name and optional data
- event handler :: a function, registered by reg-event-fx, takes coeffects map and event
- coeffects :: current state of the world
- effect handlers :: a function, actions the effects (one per key in map) returned by event handler.
- query :: function automatically called after an event, effect handled. registered by reg-sub. - matieralizes view
- view functions :: subscribe to query functions, generate hiccup which is rendered
